---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "daily"

  - package-ecosystem: "pnpm"
    directory: "/frontend/"
    target-branch: "dev"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/setup/requirements/"
    target-branch: "dev"
    schedule:
      interval: "daily"
