name: Deploy

on:
  release:
    types: [created]

jobs:
  release:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Tag Docker image
        run: |
          TAG_NAME=$(grep -oP '(?<=# \[)[^\]]+' CHANGELOG.md | head -n 1)
          echo "Tagging with $TAG_NAME"
          VERSION=v$TAG_NAME
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo NEXT_PUBLIC_FRONTEND_URL=\"https://grezy.org/\" >> frontend/.env # TODO: Change
          echo NEXT_PUBLIC_BACKEND_URL=\"https://grezy.org/\" >> frontend/.env # TODO: Change
          python -m pip install cryptography
          python ./setup/env_file_generator.py production
          make up-prod
          docker tag nextjs ghcr.io/${{ github.repository }}/nextjs:$VERSION
          docker tag nextjs ghcr.io/${{ github.repository }}/nextjs:latest
          docker tag nango ghcr.io/${{ github.repository }}/nango:$VERSION
          docker tag nango ghcr.io/${{ github.repository }}/nango:latest
            
      - name: Push Django Docker image
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          docker push ghcr.io/${{ github.repository }}/nextjs:${{ env.VERSION }}
          docker push ghcr.io/${{ github.repository }}/nextjs:latest
          docker push ghcr.io/${{ github.repository }}/nango:${{ env.VERSION }}
          docker push ghcr.io/${{ github.repository }}/nango:latest