name: Django CI

on:
  pull_request:
    paths:
      - backend/**

jobs:
  authorize:
    environment: ${{ github.event.pull_request.head.repo.full_name != github.repository && 'external' || 'internal' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: echo "Passed"

  build:
    name: Django build
    needs: authorize
    timeout-minutes: 30
    runs-on: ubuntu-latest
    environment: ${{ github.event.pull_request.head.repo.full_name != github.repository && 'external' || 'internal' }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip" # caching pip dependencies

      - name: Create ./backend/.envs/.development files
        run: |
          python -m pip install cryptography ruff
          python ./setup/env_file_generator.py development

      - name: Start containers
        run: make up

      - name: Configure Bridge
        run: make nango

      - name: Tests and coverage
        run: make coverage

      - name: Lint with ruff
        uses: chartboost/ruff-action@v1

      - name: Coverage value
        run: |
          cvg_result=$(docker exec nango_django coverage report --skip-covered | head -n -2 | tail -n 1 | awk '{print $NF}' | sed 's/%//')
          echo "COVERAGE=$cvg_result" >> $GITHUB_ENV
          echo $cvg_result

      - name: Stop containers
        if: always()
        run: make down
