name: Prod Build Check

on:
  pull_request:

jobs:
  authorize:
    environment: ${{ github.event.pull_request.head.repo.full_name != github.repository && 'external' || 'internal' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: echo "Passed"

  build:
    name: Django build
    needs: authorize
    timeout-minutes: 30
    runs-on: ubuntu-latest
    environment: ${{ github.event.pull_request.head.repo.full_name != github.repository && 'external' || 'internal' }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip" # caching pip dependencies

      - name: Create ./backend/.envs/.production files
        run: |
          python -m pip install cryptography
          python ./setup/env_file_generator.py production
          echo NEXT_PUBLIC_FRONTEND_URL=\"http://localhost:3000/\" >> frontend/.env
          echo NEXT_PUBLIC_BACKEND_URL=\"http://localhost:8000/\" >> frontend/.env

      - name: Start containers
        run: make up-prod